name: asaan_rent
description: "AsaanRent â€“ House, Shop, Office, Plot & Room Rental Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  supabase_flutter: ^2.10.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  image_picker: ^1.2.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  map_picker: ^0.0.3
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.10.0
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  path: ^1.9.1
  share_plus: ^12.0.1
  provider: ^6.1.5+1
  crop_your_image: ^2.0.0
  path_provider: ^2.1.5
  app_links: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo1.png
    - assets/logo2.png
    - assets/house.png
    - assets/icon/logoo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoo.png"
